### ISSUE TITLE
"application/json;" cannot be parsed

### ISSUE THREAD

**Issue by zyf0330** [jshttp/media-typer#3]
Does `"application/json;"` has a invalid parameter format?
I don't know actually.

**Comment by dougwilson** [comment]
Hi @zyf0330! This module is in a little flux right now, and is basically the same as the newer `content-type` module, in that the string you give it is parsed according to the rules of the HTTP Content-Type header, which can be found in RFC 7231. You can find the ABNF grammar for this string at http://tools.ietf.org/html/rfc7231#appendix-D which boils down to `type "/" subtype *( OWS ";" OWS parameter )`, which means that as soon as your have a `;` character, you actually have to have a `parameter` following it, which is what makes your string invalid (a `;` without a parameter following it).

I hope this helps!

**Comment by zyf0330** [comment]
Thanks. Now I get to find what sends out this kind of invalid request.

On Tue, Mar 1, 2016, 22:00 Douglas Wilson <notifications@github.com> wrote:

> Closed #3 <https://github.com/jshttp/media-typer/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jshttp/media-typer/issues/3#event-573061166>.
>
-- 

追随

**Comment by dougwilson** [comment]
Yea, haha. I would imagine there is some code perhaps doing something simple like the following (JavaScript): `'application/json' + ';' + parameters.join(';')` :)
