### ISSUE TITLE
Requests without content-type header make the module crash

### ISSUE THREAD

**Issue by goloroden** [jshttp/media-typer#4]
In version `0.3.0`, when you call the `parse` function and hand over a `req` object that has no `content-type` header set, this module crashes.

The problem is first located [here](https://github.com/jshttp/media-typer/blob/d49d41ffd0bb5a0655fa44a59df2ec0bfc835b16/index.js#L139-L147), where `getcontenttype` is called. Then this calls [this code](https://github.com/jshttp/media-typer/blob/d49d41ffd0bb5a0655fa44a59df2ec0bfc835b16/index.js#L208-L211), which simply returns `undefined` if the header is not there - which in turn leads to [this error message](https://github.com/jshttp/media-typer/blob/d49d41ffd0bb5a0655fa44a59df2ec0bfc835b16/index.js#L150).

I'm not that sure how to handle this case, but if you decide for an option, I'm happy to provide a PR.

**Comment by dougwilson** [comment]
Hi @goloroden , simply throwing an error is not "crashing".

Even then, there is nothing to make a PR against; that feature was removed in 317a26768755a08b292476440f16a2e2113617b2

**Comment by goloroden** [comment]
First of all, thanks for replying that quickly :-)!

Regarding the word "crashing" - you are right, it was not the correct word for what I wanted to express. Sorry for that :-(

Good to know that this behavior has changed. Are there any plans yet on when a new version will be released?

**Comment by dougwilson** [comment]
Not right now, but a new version would not actually be useful, since a new version would no longer allow you to even pass in a `req` object to this module.

**Comment by dougwilson** [comment]
> [...] a new version would not actually be useful

Sorry, what I meant here was a new published version would not be useful to solving the issue you raised. If I published this as 0.4.0 and you upgraded, you'll get an error that `req` itself is not a string and you'll have to completely change your code.

If you want to actually pass in the `req` object, I recommend following that commit, which is to simply switch your use to the `content-type` module rather than this one :)

**Comment by goloroden** [comment]
I got that ;-)

My question regarding a new version was more out of curiosity, because this means updating my code (rather today than tomorrow ;-)).

**Comment by dougwilson** [comment]
Hm.. I'm not quite sure what the difference would be? The `content-type` module has the exact same behavior.

**Comment by goloroden** [comment]
As said, it was more out of curiosity.

The difference would only be to be forced to update the code if you follow an "always use the latest version"-policy.

So, no need to do anything right now :-)

**Comment by dougwilson** [comment]
Ah, gotcha. Yea, the new version hasn't been released since issue #2 just needs to be addressed first.

**Comment by goloroden** [comment]
I see :-)

Thanks for taking your time to reply to my issue that much :-))
