### ISSUE TITLE
Receive `TypeError: invalid media type` on MIME-types

### ISSUE THREAD

**Issue by Borewit** [jshttp/media-typer#8]
Version [v1.0.1](https://github.com/jshttp/media-typer/releases/tag/v1.0.1) breaks my unit tests, following mime types do no longer parse:
1. `message/external-body; access-type=URL`, taken from [RFC 2017](https://tools.ietf.org/rfc/rfc2017.txt), line 96
2. `Text/HTML;Charset="utf-8"`

Following error is throws: `TypeError: invalid media type`

Blocks: Borewit/music-metadata#155

**Comment by dougwilson** [comment]
https://github.com/jshttp/media-typer/blob/master/HISTORY.md#100--2018-10-20
