### ISSUE TITLE
Content-Types with parameters should not be invalid

### ISSUE THREAD

**Issue by KamalAman** [jshttp/media-typer#9]
Content-Type of `application/xml; name=123` should be valid according to [RFC 2045](https://www.ietf.org/rfc/rfc2045.txt), Content-Types should support parameters `type "/" subtype *(";" parameter)` 

However if you run `var obj = typer.parse('application/xml; name=123')`
you get the following error `invalid media type`

**Comment by dougwilson** [comment]
This module is for RFC 6838, which doesn't have a parameter format. You're looking for a module to parse the HTTP `content-type` header: https://github.com/jshttp/content-type
